# ===== DB 연결 설정 =====
# TODO 2-01A: DataSource 설정 — driver-class-name, url, username, password 4종
#             (DB 이름: ssafydb / 계정 ID: ssafy / 비밀번호: ssafy)
#             URL 옵션: useSSL=false & serverTimezone=UTC & allowPublicKeyRetrieval=true 권장
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ssafydb
spring.datasource.username=ssafy
spring.datasource.password=ssafy

# ===== JSP 뷰 리졸버 =====
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


# ===== MyBatis 설정 =====
# TODO 2-01C: Mapper XML 위치 — mybatis.mapper-locations
#             (classpath 의 mappers 폴더 아래 *.xml 와일드카드)
mybatis.mapper-locations=classpath:mappers/*.xml


# TODO 2-01D: DTO 패키지에 타입 별칭 자동 등록 — mybatis.type-aliases-package
mybatis.type-aliases-package=com.ssafy.board.model.dto

# TODO 2-01E: snake_case <-> camelCase 자동 매핑 활성화 (* 핵심 옵션!)
#             mybatis.configuration.map-underscore-to-camel-case
mybatis.configuration.map-underscore-to-camel-case=true